import { launch, openApp, ok, done } from './lib.mjs';
const b = await launch();
const { p, errors } = await openApp(b, { blank: false });
// はじめて開くと見本の世界。白紙の世界を作って試す
ok(await p.evaluate(() => Object.keys(__app.world.notes).length > 10), 'first run opens the sample world');
await p.evaluate(() => __app.createWorld('browser', 'テスト')); await p.waitForTimeout(300);
await p.click('nav button[data-id="notes"]');
await p.click('#newNote');
await p.fill('.ne-title', 'ナイアーラトテップ');
await p.locator('.ne-title').press('Tab');
await p.fill('.ne-tags input', 'NPC'); await p.keyboard.press('Enter');
await p.waitForTimeout(200);
ok(await p.locator('.tpl-grid').count() === 1, 'CoC6 template fields appear for tag NPC');
await p.fill('.tpl-grid input >> nth=0', '神父');
await p.fill('.ne-body', '# 正体\n**這い寄る混沌**。[[アーカム]]に現れる');
await p.locator('.ne-body').blur();
await p.click('.md-tools button:has-text("表示")');
ok(await p.locator('.md h3').textContent() === '正体', 'markdown heading');
ok(await p.locator('.md a.nlink.missing').count() === 1, 'missing link shown');
await p.click('.md a.nlink.missing');
await p.waitForTimeout(200);
ok(await p.evaluate(() => Object.values(__app.world.notes).some(n => n.title === 'アーカム')), 'clicking missing link creates note');
await p.waitForTimeout(1600);
await p.reload(); await p.waitForFunction(() => window.__app && document.getElementById('worldName').textContent !== '…'); await p.waitForTimeout(300);
const titles = await p.evaluate(() => Object.values(__app.world.notes).map(n => n.title).sort().join());
ok(titles === 'アーカム,ナイアーラトテップ', 'notes persisted across reload: ' + titles);
ok(await p.locator('.ncard').count() === 2, 'list shows 2 cards');
const n = await p.evaluate(() => Object.values(__app.world.notes).find(n => n.title === 'ナイアーラトテップ'));
ok(n.fields['職業'] === '神父' && n.tags[0] === 'NPC', 'fields saved');
await p.keyboard.press('Control+z'); await p.waitForTimeout(100);
ok(await p.evaluate(() => __app.store.canUndo()) === false, 'history cleared after reload (fresh session)');
await p.screenshot({ path: '/tmp/claude-0/-home-user-TRPG/d9632758-4ca0-5713-8fd6-526324b6f925/scratchpad/app-notes.png' });
ok(!errors.filter(e => !/settings\.js|drive\.js|board\.js|timemap/.test(e)).length, 'errors: ' + errors.join('\n'));
await b.close(); done();
